export const copy = {
  studio: "Zprávy",
  tagline: (from: string, channel: string) =>
    channel === "imessage"
      ? `iMessage z ${from}. Na Android spadne na RCS nebo SMS. Koncepty zůstanou v tomto zařízení.`
      : channel === "whatsapp"
        ? `WhatsApp z ${from || "Cloud API"}. První zpráva na nový kontakt jde jako schválená šablona.`
        : `SMS z ${from} přes MailerSend. Jen USA a Kanada.`,
  write: "Napsat zprávu",
  to: "Komu",
  toPlaceholder: "+420 722 426 195",
  toPlaceholderSms: "+1 415 555 0134",
  toHint: "České číslo stačí bez předvolby. iMessage jde kamkoliv.",
  toHintSms: "Jedno nebo více čísel, oddělených čárkou. Jen USA a Kanada.",
  toHintWhatsapp: "Libovolné číslo s WhatsApp. První zpráva může jít jako šablona.",
  sendWhatsapp: "Odeslat WhatsApp",
  viaWhatsapp: "WhatsApp",
  waSetup: "WhatsApp Business",
  waSetupDesc:
    "MailerSend WhatsApp na tomhle tokenu nejde (403). Vložte Phone Number ID a token EAA z Meta App Dashboard.",
  waPhoneId: "Phone Number ID",
  waToken: "Cloud API token",
  waTemplate: "Šablona",
  waLanguage: "Jazyk šablony",
  waConnect: "Ověřit a uložit",
  waConnecting: "Ověřuji",
  waConnected: "WhatsApp je připojený",
  channelsHint: "iMessage je živé. WhatsApp se nastaví v Nastavení.",
  channels: "Kanály",
  textThisLine: "Text na tuto linku",
  message: "Zpráva",
  messagePlaceholder: "Pište stručně. Pro jméno z Lidi použijte {{name}}.",
  insertName: "Vložit jméno",
  hello: "Ahoj",
  code: "Kód",
  reminder: "Připomínka",
  saveTemplate: "Uložit šablonu",
  send: "Odeslat SMS",
  sendIMessage: "Odeslat iMessage",
  sending: "Odesílám",
  sendN: (n: number) => (n > 1 ? `Odeslat ${n} SMS` : "Odeslat SMS"),
  viaIMessage: "iMessage",
  viaSms: "SMS",
  viaRcs: "RCS",
  lookupFail: "Službu se nepodařilo zjistit.",
  confirmHint: "Před odesláním to ještě potvrdíte.",
  outbox: "Odchozí",
  clear: "Smazat",
  loading: "Načítám seznam…",
  emptyOutbox:
    "Zatím nic neodešlo. Po odeslání tady uvidíte stav a můžete ho obnovit z MailerSend.",
  search: "Hledat v odchozích",
  today: (msgs: number, segs: number) => `Dnes ${msgs} · ${segs} SMS`,
  resend: "Znovu",
  status: "Stav",
  copy: "Kopírovat",
  people: "Lidé",
  peopleTitle: "Lidé",
  peopleDesc:
    "Pojmenujte číslo v poli Komu. Pak stačí klepnout na jméno a vyplní se samo.",
  name: "Jméno",
  namePlaceholder: "Alex",
  savePerson: "Uložit osobu",
  noPeople: "Zatím tu nikdo není.",
  settings: "Nastavení",
  channelNeeds: "Co je potřeba",
  channelLive: "Živé",
  channelProvision: "Čeká",
  channelPartner: "Partner",
  channelClosed: "Zavřené",
  settingsDesc: "Podpis se připojí pod každou odeslanou zprávu.",
  signature: "Podpis",
  signaturePlaceholder: "— Wire",
  confirmToggle: "Před odesláním potvrdit",
  confirmTitle: "Odeslat tuto zprávu?",
  confirmBody: (who: string, segs: number, from: string, channel: string) =>
    `Komu ${who}. ${
      channel === "imessage"
        ? "iMessage"
        : channel === "whatsapp"
          ? "WhatsApp"
          : `${segs} SMS`
    } z ${from}.`,
  emptyMessage: "Prázdná zpráva",
  cancel: "Zrušit",
  sendNow: "Odeslat teď",
  templateTitle: "Název šablony",
  templatePlaceholder: "Např. Otevírací doba",
  save: "Uložit",
  max: "2048 max",
  smsCount: (n: number, enc: string) => `${n} SMS · ${enc}`,
  chars: (n: number) => `${n} znaků`,
  leftInSms: (left: number, n: number) => `zbývá ${left} v SMS ${n}`,
  removeBraces: "Odstraňte složené závorky, nebo použijte jen {{name}}.",
  live: "Živé",
  paused: "Pozastaveno",
  offline: "Offline",
  connecting: "Připojuji",
  queued: "Ve frontě",
  processed: "Zpracováno",
  sent: "Odesláno",
  failed: "Selhalo",
  pullHistory: "Načíst",
  loadedResend: "Připraveno k opětovnému odeslání",
  savedPerson: (name: string) => `Uloženo: ${name}`,
  savedTemplate: "Šablona uložena",
  copied: (label: string) => `${label} zkopírováno`,
  copyFail: "Nepodařilo se zkopírovat.",
  updated: (status: string) => `Aktualizováno: ${status}`,
  noId: "U této zprávy chybí ID z MailerSend.",
  offlineErr: "MailerSend je offline.",
  pausedErr: "Toto SMS číslo je pozastavené.",
  writeFirst: "Nejdřív napište zprávu.",
  validNumber: "Nejdřív zadejte platné číslo USA nebo Kanady.",
  giveName: "Dejte tomuto číslu jméno.",
  needNameToken:
    "Pro {{name}} uložte každého příjemce mezi Lidi.",
  refreshFail: "Stav se nepodařilo obnovit.",
  sendFail: "Odeslání selhalo.",
  historyFail: "Historii se nepodařilo načíst.",
  historyOk: (n: number) =>
    n === 0 ? "Žádné nové zprávy." : `Načteno ${n} zpráv.`,
  close: "Zavřít",
  removePerson: (name: string) => `Odebrat ${name}`,
  clearOutbox: "Smazat odchozí",
  messageLabel: "Zpráva",
  helloBody: "Ahoj z Wire. Tohle je testovací zpráva.",
  codeBody: (code: string) =>
    `Váš kód je ${code}. Platí 10 minut.`,
  reminderBody:
    "Připomínka: pořád to platí. Odpovězte, pokud to potřebujete přesunout.",
  invalidNumber: "Zadejte celé číslo s předvolbou.",
  usCaOnly: "MailerSend SMS doručuje jen do USA a Kanady.",
  tooMany: "Najednou lze oslovit nejvýš 8 čísel.",
  oneInvalid: "Některé číslo není v pořádku.",
} as const;

export const statusLabel: Record<
  "queued" | "processed" | "sent" | "failed" | "paused",
  string
> = {
  queued: copy.queued,
  processed: copy.processed,
  sent: copy.sent,
  failed: copy.failed,
  paused: copy.paused,
};
