export const copy = {
  studio: "SMS ateliér",
  tagline: (from: string) =>
    `Odesíláte z ${from}. Koncepty a lidé zůstanou v tomto zařízení. Příjemci jen USA a Kanada.`,
  write: "Napsat zprávu",
  to: "Komu",
  toPlaceholder: "+1 415 555 0134, +1 212 555 0199",
  toHint: "Jedno nebo více čísel, oddělených čárkou. Jen USA a Kanada.",
  textThisLine: "Text na tuto linku",
  message: "Zpráva",
  messagePlaceholder: "Pište stručně. Pro jméno z Lidi použijte {{name}}.",
  insertName: "Vložit jméno",
  hello: "Ahoj",
  code: "Kód",
  reminder: "Připomínka",
  saveTemplate: "Uložit šablonu",
  send: "Odeslat SMS",
  sending: "Odesílám",
  sendN: (n: number) => (n > 1 ? `Odeslat ${n} SMS` : "Odeslat SMS"),
  confirmHint: "Před odesláním to ještě potvrdíte.",
  outbox: "Odchozí",
  clear: "Smazat",
  loading: "Načítám seznam…",
  emptyOutbox:
    "Zatím nic neodešlo. Po odeslání tady uvidíte stav a můžete ho obnovit z MailerSend.",
  search: "Hledat v odchozích",
  today: (msgs: number, segs: number) => `Dnes ${msgs} · ${segs} SMS`,
  resend: "Znovu",
  status: "Stav",
  copy: "Kopírovat",
  people: "Lidé",
  peopleTitle: "Lidé",
  peopleDesc:
    "Pojmenujte číslo v poli Komu. Pak stačí klepnout na jméno a vyplní se samo.",
  name: "Jméno",
  namePlaceholder: "Alex",
  savePerson: "Uložit osobu",
  noPeople: "Zatím tu nikdo není.",
  settings: "Nastavení",
  settingsDesc: "Podpis se připojí pod každou odeslanou zprávu.",
  signature: "Podpis",
  signaturePlaceholder: "— Wire",
  confirmToggle: "Před odesláním potvrdit",
  confirmTitle: "Odeslat tuto zprávu?",
  confirmBody: (who: string, segs: number, from: string) =>
    `Komu ${who}. ${segs} SMS z ${from}.`,
  emptyMessage: "Prázdná zpráva",
  cancel: "Zrušit",
  sendNow: "Odeslat teď",
  templateTitle: "Název šablony",
  templatePlaceholder: "Např. Otevírací doba",
  save: "Uložit",
  max: "2048 max",
  smsCount: (n: number, enc: string) => `${n} SMS · ${enc}`,
  chars: (n: number) => `${n} znaků`,
  leftInSms: (left: number, n: number) => `zbývá ${left} v SMS ${n}`,
  removeBraces: "Odstraňte složené závorky, nebo použijte jen {{name}}.",
  live: "Živé",
  paused: "Pozastaveno",
  offline: "Offline",
  connecting: "Připojuji",
  queued: "Ve frontě",
  processed: "Zpracováno",
  sent: "Odesláno",
  failed: "Selhalo",
  pullHistory: "Načíst",
  loadedResend: "Připraveno k opětovnému odeslání",
  savedPerson: (name: string) => `Uloženo: ${name}`,
  savedTemplate: "Šablona uložena",
  copied: (label: string) => `${label} zkopírováno`,
  copyFail: "Nepodařilo se zkopírovat.",
  updated: (status: string) => `Aktualizováno: ${status}`,
  noId: "U této zprávy chybí ID z MailerSend.",
  offlineErr: "MailerSend je offline.",
  pausedErr: "Toto SMS číslo je pozastavené.",
  writeFirst: "Nejdřív napište zprávu.",
  validNumber: "Nejdřív zadejte platné číslo USA nebo Kanady.",
  giveName: "Dejte tomuto číslu jméno.",
  needNameToken:
    "Pro {{name}} uložte každého příjemce mezi Lidi.",
  refreshFail: "Stav se nepodařilo obnovit.",
  sendFail: "Odeslání selhalo.",
  historyFail: "Historii se nepodařilo načíst.",
  historyOk: (n: number) =>
    n === 0 ? "Žádné nové zprávy." : `Načteno ${n} zpráv.`,
  close: "Zavřít",
  removePerson: (name: string) => `Odebrat ${name}`,
  clearOutbox: "Smazat odchozí",
  messageLabel: "Zpráva",
  helloBody: "Ahoj z Wire. Tohle je testovací zpráva.",
  codeBody: (code: string) =>
    `Váš kód je ${code}. Platí 10 minut.`,
  reminderBody:
    "Připomínka: pořád to platí. Odpovězte, pokud to potřebujete přesunout.",
  invalidNumber: "Zadejte celé číslo s předvolbou.",
  usCaOnly: "MailerSend SMS doručuje jen do USA a Kanady.",
  tooMany: "Najednou lze oslovit nejvýš 8 čísel.",
  oneInvalid: "Některé číslo není v pořádku.",
} as const;

export const statusLabel: Record<
  "queued" | "processed" | "sent" | "failed" | "paused",
  string
> = {
  queued: copy.queued,
  processed: copy.processed,
  sent: copy.sent,
  failed: copy.failed,
  paused: copy.paused,
};
